### ISSUE TITLE
Error message when using 3.6.8

### ISSUE THREAD

**Issue by haferburg** [brechtm/rinohtype#285] opened 2021-08-30 09:41 UTC
https://devguide.python.org/#status-of-python-branches lists 3.6 as still supported (not EOL).

```
$ pip install rinohtype
Collecting rinohtype
  Using cached https://files.pythonhosted.org/packages/5f/12/96f564c61b1ac23a8927a40af5b4207e80dd87c73b28060f1d6aea772201/rinohtype-0.5.3-py3-none-any.whl
[...]

$ rinoh
Traceback (most recent call last):
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AHaferbu\.pyenv\pyenv-win\versions\3.6.8\Scripts\rinoh.exe\__main__.py", line 5, in <module>
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\__init__.py", line 41, in <module>
    from . import resource
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\resource.py", line 205, in <module>
    from .template import DocumentTemplate
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\template.py", line 42, in <module>
    from .stylesheets import sphinx
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\stylesheets\__init__.py", line 42, in <module>
    .format(stylesheet.description, stylesheet))
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\style.py", line 670, in __str__
    for name, entry_point in self.installed_resources:
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\rinoh\resource.py", line 54, in installed_resources
    for entry_point in ilm.entry_points()[cls.entry_point_group]:
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\__init__.py", line 1019, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\__init__.py", line 472, in load
    ordered = sorted(eps, key=by_group)
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\__init__.py", line 1017, in <genexpr>
    dist.entry_points for dist in unique(distributions())
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\__init__.py", line 635, in _normalized_name
    return Prepared.normalize(self.name)
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\importlib_metadata\__init__.py", line 875, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "c:\users\ahaferbu\.pyenv\pyenv-win\versions\3.6.8\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

If you don't support 3.6, it would be nice if you could update the landing page.

**Comment by brechtm** [comment] 2021-09-02 09:49
rinohtype does support Python 3.6. I can't reproduce this on macOS with CPython 3.6.14, so this looks like it may be limited to Windows. I can verify after my vacation late September.

P.S. Please use the issue templates.

**Comment by brechtm** [comment] 2021-10-01 16:44
I can reproduce this. Same exception on Python 3.7. I'll try to fix this next week...

**Comment by brechtm** [comment] 2021-10-05 16:44
Not a rinohtype bug. It occurs in _importlib-metadata_ starting from version 4.3.0.
- [ ] adjust version constraints for this dependency
- [ ] report at _importlib-metadata_'s issue tracker

**Comment by brechtm** [comment] 2021-10-06 08:16
Actually, the master branch is already fixed to work with these newer _importlib-metadata_ versions (b2ddaab64e3f27bc2113fd663471bae4ae4efd99). It was just a bit difficult to diagnose Anyway, this will be fixed in the upcoming release.

**Closed by brechtm** 2021-10-06 08:16 UTC
Labels: bug, crash

**Comment by tilusnet** [comment] 2022-01-27 19:12
I am having the same problem.
Should I build from source in order to get this bug fixed?

I'm on Python 3.7 and installed `rinohtype` 0.5.3 with `pip`.

**Comment by dmg0345** [comment] 2022-02-07 19:08
> I am having the same problem. Should I build from source in order to get this bug fixed?
> 
> I'm on Python 3.7 and installed `rinohtype` 0.5.3 with `pip`.

Try installing the master branch, it fixed it for me.

pip install git+https://github.com/brechtm/rinohtype.git@master

**Comment by brechtm** [comment] 2022-03-07 12:45
This is equivalent but requires less data to be transferred and doesn't require git:

```bash
pip install https://github.com/brechtm/rinohtype/archive/refs/heads/master.zip
```

I hope to release 0.5.4 soon, but don't wait for that :-)
