### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by frol** [brechtm/rinohtype#14] opened 2016-02-28 03:52 UTC
demo.txt:

```rst
.. [#label] Footnotes may be numbered, either manually (as in [1]_) or
   automatically using a "#"-prefixed label.  This footnote has a
   label so it can be referred to from multiple places, both as a
   footnote reference ([#label]_) and as a hyperlink reference
   (label_).
```

```
$ rinoh demo.txt
qq.txt:1: (ERROR/3) Unknown target name: "1".
RinohType 0.1.3-154-g264f (Feb 28 2016, 09:57:09)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
No style 'table of contents title' found in stylesheet
No style 'table of contents title' found in stylesheet
No style 'table of contents title' found in stylesheet
Traceback (most recent call last):
  File "env3/bin/rinoh", line 5, in <module>
    main()
  File "env3/lib/python3.5/site-packages/rinoh/tool.py", line 44, in main
    document.render(input_root)
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 360, in render
    section_num_pages = self.render_pages(_sections)
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 386, in render_pages
    section_page_count = section.render(sum(section_page_counts))
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 235, in render
    part_page_count = part.render(doc_page_count + section_page_count)
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 171, in render
    chains_requiring_new_page = set(chain for chain in page.render())
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 171, in <genexpr>
    chains_requiring_new_page = set(chain for chain in page.render())
  File "env3/lib/python3.5/site-packages/rinoh/document.py", line 117, in render
    for chain in super().render(rerender=index > 0):
  File "env3/lib/python3.5/site-packages/rinoh/layout.py", line 178, in render
    for chain in child.render(rerender):
  File "env3/lib/python3.5/site-packages/rinoh/layout.py", line 178, in render
    for chain in child.render(rerender):
  File "env3/lib/python3.5/site-packages/rinoh/layout.py", line 278, in render
    last_descender=last_descender):
  File "env3/lib/python3.5/site-packages/rinoh/layout.py", line 557, in render
    self._state.flowable_state)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 125, in flow
    state=state, **kwargs)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 348, in render
    render_content(maybe_container, last_descender)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 334, in render_content
    descender, state=state)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 125, in flow
    state=state, **kwargs)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 244, in render
    state=state.first_flowable_state, **kwargs)
  File "env3/lib/python3.5/site-packages/rinoh/flowable.py", line 125, in flow
    state=state, **kwargs)
  ...
  File "env3/lib/python3.5/site-packages/rinoh/paragraph.py", line 260, in render
    line_width = float(container.width)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 129, in __float__
    return float(self.minuend) - float(self.subtrahend)
  File "env3/lib/python3.5/site-packages/rinoh/dimension.py", line 109, in __float__
    return float(self._value)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by brechtm** [comment] 2016-06-30 13:08
This doesn't crash the current master branch. If the footnote is referenced, we do end up in the same infinite recursion:

```
Reference the footnote [#label]_.

.. [#label] Footnotes may be numbered, either manually (as in [1]_) or
   automatically using a "#"-prefixed label.  This footnote has a
   label so it can be referred to from multiple places, both as a
   footnote reference ([#label]_) and as a hyperlink reference
   (label_).
```

**Comment by brechtm** [comment] 2016-07-11 10:31
Duplicate of #19

**Closed by brechtm** 2016-07-11 10:31 UTC
Labels: bug
