### ISSUE TITLE
rinohtype not correctly processing document links

### ISSUE THREAD

**Issue by techauthoruk** [brechtm/rinohtype#373] opened 2022-10-21 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### PDF produced by rinohtype

If I produce my Sphinx output using LaTeX, internal links are displayed correctly (i.e. they show the correct section/subsection names) as in this example:

![latex](https://user-images.githubusercontent.com/57015243/197201074-9b3cfdc2-8f9d-4300-b1d3-69a99f76f510.png)

When I process the same document using rinohtype, the section link just displays a chapter title:

![rinoh](https://user-images.githubusercontent.com/57015243/197201255-9819a7cb-4124-4475-b7cb-2e1e8217b6a5.png)

I would expect all the internal links to display in rinohtype in the same way they do in LaTeX.

### Source files

See the screenshots above

### Versions

```text
rinohtype 0.5.5 (in development)
Sphinx 5.1.1
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
```

**Comment by brechtm** [comment] 2022-10-24 16:18
This changed in 0.5.2, as I reasoned this is how references are traditionally made in print (since you  didn't have hyperlinks back then). I can see how this can be confusing however, since the output differs from the HTML output. I was wondering how the LaTeX builder handled these!

Please see these links on how to adjust the style sheet to output named links instead:
- #244
- [Rinohtype link text is "Section 3.1" instead of the text specified in the link or link target](https://stackoverflow.com/questions/68571864/rinohtype-link-text-is-section-3-1-instead-of-the-text-specified-in-the-link-o)

Closing as duplicate of #244

**Closed by brechtm** 2022-10-24 16:18 UTC
Labels: question, faq

**Comment by techauthoruk** [comment] 2022-10-25 10:02
Thanks for this @brechtm 

I am obviously making some basic error here. If I add:

```bash
[linked reference]
type = custom
```

to the (global) `Sphinx.rts` file, the inline references are resolved correctly for my use case. I created a custom file which sits in the `Source` directory with my content. It's correctly referenced in `conf.py`, but adding the linked reference part is ignored.

So my `conf.py` has this:

```python
rinoh_documents = [dict(doc='index',        # top-level file (index.rst)
                        target='manual',
                        template='SEaB.rtt',
                        stylesheet='SEaB.rts',  
                        title='FLEXIBUSTER',
                        author='Operating and Maintenance Manual',
                        logo='img/logo.png')]
```
In my custom stylesheet I have added:

```python
[STYLESHEET]
name = SEaB custom style
base = sphinx

[linked reference]
type = custom
;this seems to make no difference - only applies from base stylesheet
```

but it doesn't get applied. Obviously me who is missing something, but I don't know what!

**Comment by brechtm** [comment] 2022-10-26 08:20
[`rinoh_documents`](http://www.mos6581.org/rinohtype/master/sphinx.html#confval-rinoh_documents) doesn't take a _stylesheet_. You need to set the style sheet in your template configuration file.
