### ISSUE TITLE
rinoh shouldn't require absolute paths for the template and style sheet

### ISSUE THREAD

**Issue by kfrajtak** [brechtm/rinohtype#253] opened 2021-05-06 10:55 UTC
When I run `rinoh -s mystyle.rst index.rst` I get 

```
ValueError: StyleSheetFile path should be absolute: mystyle.rst
```

`mystyle.rst` is in current directory

Please add CLI example to http://www.mos6581.org/rinohtype/master/basicstyling.html chapter.

**Comment by brechtm** [comment] 2021-05-06 12:07
This is indeed not the intended behavior. This is a regression introduced with recent changes.

**Comment by brechtm** [comment] 2021-06-23 08:20
Fixed in #266

**Closed by brechtm** 2021-06-23 08:20 UTC
Labels: bug, rinoh
