### ISSUE TITLE
AttributeError: No such element: styled_text in <rinoh.frontend.rst.nodes.Definition_List object at 0x7fbbd5e7ebd0>

### ISSUE THREAD

**Issue by thiagocrepaldi** [brechtm/rinohtype#171] opened 2020-07-01 23:19 UTC
The PDF renderization was working on ubuntu 18.04 with sphinx 3.1.0 and rinohtype 0.4.0
After upgrading to ubuntu 20.04, the crash below happened

This discussion on Google Groups might help https://groups.google.com/g/sphinx-users/c/Sl1nX_bwR7c

1. The **messages** output by rinohtype (and Sphinx) when rendering the
   document.
```bash
[ 66%] Generating PDF documentation with Sphinx
Running Sphinx v3.1.1
/home/thiagofc/dev/devops/ORT-Frontend-Design/docs/conf.py:46: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet('custom.css')
'rinoh_documents' config variable not set, automatically converting from 'latex_documents'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
loading pickled environment... 'rinoh_elements/papersize' config variable not set, automatically converting from 'latex_elements/papersize'
'rinoh_logo' config variable not set, automatically converting from 'latex_logo'
'rinoh_domain_indices' config variable not set, automatically converting from 'latex_domain_indices'
done
building [mo]: targets for 0 po files that are out of date
building [rinoh]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing ort_frontend_functional_and_design_specs... index content resolving references...
rendering... 

Exception occurred:
  File "/home/thiagofc/miniconda3/envs/ort_py37/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 42, in __getattr__
    raise AttributeError('No such element: {} in {}'.format(name, self))
AttributeError: No such element: styled_text in <rinoh.frontend.rst.nodes.Definition_List object at 0x7fbbd5e7ebd0>
The full traceback has been saved in /tmp/sphinx-err-x8p7o9fq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[2]: *** [docs/CMakeFiles/Sphinx.dir/build.make:69: docs/sphinx/ort_frontend_functional_and_design_specs.pdf] Error 2
make[1]: *** [CMakeFiles/Makefile2:91: docs/CMakeFiles/Sphinx.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

Please also provide the following information:
* rinohtype version: 0.4.1 and 0.4.2.dev0+62e9856a
* Sphinx version: 3.1.1
* Python version: 3.7.7
* operating system: Ubuntu 20.04 (it was working on Ubuntu 18.04 with slightly older versions of sphinx and rinohtype)

Full log:
```bash
 version: 2.11.2
# Last messages:
#   building [rinoh]: all documents
#   updating environment:
#   0 added, 0 changed, 0 removed
#   looking for now-outdated files...
#   none found
#   processing frontend_functional_and_design_specs...
#   index
#   content
#   resolving references...
#   rendering...
# Loaded extensions:
#   sphinx.ext.mathjax (3.1.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/myuser/miniconda3/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.intersphinx (3.1.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   rinoh.frontend.sphinx (0.4.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/__init__.py
#   sphinx.ext.autodoc.type_comment (3.1.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.1.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (3.1.1) from /home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(['__all__'], to_build)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/__init__.py", line 224, in write
    self.write_doc(docname, doctree, docnames, targetname)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/__init__.py", line 230, in write_doc
    sphinx_builder=self)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 131, in from_doctree
    flowables = mapped_tree.children_flowables()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/nodes.py", line 232, in build_flowable
    return super().build_flowable(id='%' + self.get('docname'), **kwargs)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/nodes.py", line 289, in build_flowable
    description = self.desc_content.flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 131, in flowable
    flowable, = self.flowables()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/sphinx/nodes.py", line 289, in build_flowable
    description = self.desc_content.flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 131, in flowable
    flowable, = self.flowables()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/nodes.py", line 531, in build_flowable
    return rt.LabeledFlowable(label, self.field_body.flowable())
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 131, in flowable
    flowable, = self.flowables()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 161, in build_flowable
    return self.grouped_flowables_class(self.children_flowables(),
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 124, in children_flowables
    return list(chain(*(item.flowables() for item in children)))
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 85, in flowables
    for flowable in super().flowables():
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 136, in flowables
    for i, flowable in enumerate(self.build_flowables()):
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 145, in build_flowables
    yield self.build_flowable()
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/nodes.py", line 210, in build_flowable
    return rt.Paragraph(self.process_content(), style=self.style)
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 64, in process_content
    return MixedStyledText([text for text in children_text if text],
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 64, in <listcomp>
    return MixedStyledText([text for text in children_text if text],
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/rst/__init__.py", line 63, in <genexpr>
    children_text = (child.styled_text() for child in self.getchildren())
  File "/home/myuser/miniconda3/lib/python3.7/site-packages/rinoh/frontend/__init__.py", line 42, in __getattr__
    raise AttributeError('No such element: {} in {}'.format(name, self))
AttributeError: No such element: styled_text in <rinoh.frontend.rst.nodes.Definition_List object at 0x7fbbd5e7ebd0>
```

**Comment by brechtm** [comment] 2020-07-02 07:44
Thanks! I'll try to fix this regression ASAP.

Can you provide the Sphinx project that triggers this crash? I'm at a loss to find the cause without it.

**Comment by brechtm** [comment] 2020-07-02 08:49
From the stack trace, it seems like there is a definition list inside of a paragraph. As far as I know, this should not occur in a docutils document tree.

**Comment by thiagocrepaldi** [comment] 2020-07-06 16:56
I isolated the issue, Brecht!

I have a RST file that has this:

```python
API Surface Overview
--------------------

.. automodule:: my_stuff
   :members:
   :undoc-members:
   :show-inheritance:
   :inherited-members:
   :member-order: bysource
```

than my my_stuff.py has this:
```python
class DummyClass(object):
    r"""Base class for implementing custom stuff

    Dummy can be either statefull or stateless.
    Stateless implementations can only rely on information available at
    :py:class:`.InternalClass1` and :py:attr:`.arg1`.
    Statefull, on the other hand, can store more parameters by overriding
    the constructor.

    In both cases, once dummy is configured, no user code is needed
    to update stuff during execution.

    NOTE: This class should never be instantiated, but used as an abstract class.

    NOTE: Current implementation doesn't support 'Xmas'.

    Args:
        arg1 (MyClass1): stuff config.
            Description on second line.
    """

    def __init__(self, arg1):
        pass

    def get_stuff(self, input):
        r"""Returns a list of stuff

        Args:
            input (:py:class:`.InternalClass1`): runtime info for current stuff

        Returns:
            ordered :py:obj:`list` of all stuff in the universe.
                The first entry is the default stuff and the remaining,
                refer to each :py:class:`MyClass1`s parameter.
                NOTE: Currently, only the default stuff is supported, 
                which implies returning a list with a single value.
        """
        raise NotImplementedError

    def get_last_stuff(self):
        r""" Return last computed learning rate by LR Scheduler"""
        pass
```
which fails in due to the indentation of the lines within `Returns:`. This class has a single return value, but I broke the explanation text in several lines and indented the 2nd to 5th lines for clarity, so that users dont think each line is a different return value


If I change the documentation as below, it works again:

```python
class DummyClass(object):
    r"""Base class for implementing custom stuff

    Dummy can be either statefull or stateless.
    Stateless implementations can only rely on information available at
    :py:class:`.InternalClass1` and :py:attr:`.arg1`.
    Statefull, on the other hand, can store more parameters by overriding
    the constructor.

    In both cases, once dummy is configured, no user code is needed
    to update stuff during execution.

    NOTE: This class should never be instantiated, but used as an abstract class.

    NOTE: Current implementation doesn't support 'Xmas'.

    Args:
        arg1 (MyClass1): stuff config.
            Description on second line.
    """

    def __init__(self, arg1):
        pass

    def get_stuff(self, input):
        r"""Returns a list of stuff

        Args:
            input (:py:class:`.InternalClass1`): runtime info for current stuff

        Returns:
            ordered :py:obj:`list` of all stuff in the universe.
            The first entry is the default stuff and the remaining,
            refer to each :py:class:`MyClass1`s parameter.
            NOTE: Currently, only the default stuff is supported, 
            which implies returning a list with a single value.
        """
        raise NotImplementedError

    def get_last_stuff(self):
        r""" Return last computed stuff"""
        pass
```

**Comment by brechtm** [comment] 2020-07-07 10:44
Great! I can imagine that was not so obvious and took some time to figure out!

I believe this may be a bug in Sphinx's napoleon extension, creating an invalid docutils document tree. AFAIK docutils and Sphinx do not check the validity of a document tree.

What happens if you build a PDF using Sphinx's LaTeX builder? I assume the HTML builder doesn't complain (I've encountered a case before where the HTML builder doesn't trip over an invalid document tree)?

**Comment by brechtm** [comment] 2020-07-07 10:46
Possible related: https://github.com/sphinx-doc/sphinx/issues/4016

**Comment by brechtm** [comment] 2020-07-07 12:55
Responding to the question you sent me by mail:

> It is funny that this stopped working on newer versions, ...

This is unlikely to be caused by any changes since rinohtype 0.4.0. Perhaps you also upgraded Sphinx? This is easy to check, of course.

**Comment by thiagocrepaldi** [comment] 2020-07-07 16:32
I have updated sphinx to 3.1.2, the latest available, and I could repro the issue.
But here is something interesting

at

```python
    def get_stuff(self, input):
        r"""Returns a list of stuff

        Args:
            input (:py:class:`.InternalClass1`): runtime info for current stuff

        Returns:
            ordered :py:obj:`list` of all stuff in the universe.
            The first entry is the default stuff and the remaining,
            refer to each :py:class:`MyClass1`s parameter.
            NOTE: Currently, only the default stuff is supported, 
            which implies returning a list with a single value.
        """
        raise NotImplementedError
```

If I replace `Returns:` by `Test:`, the PDF is generated. If I try `Returns :` it also works.

**Comment by thiagocrepaldi** [comment] 2020-07-07 16:33
> Great! I can imagine that was not so obvious and took some time to figure out!
> 
> I believe this may be a bug in Sphinx's napoleon extension, creating an invalid docutils document tree. AFAIK docutils and Sphinx do not check the validity of a document tree.
> 
> What happens if you build a PDF using Sphinx's LaTeX builder? I assume the HTML builder doesn't complain (I've encountered a case before where the HTML builder doesn't trip over an invalid document tree)?

The HTML is built as expected, but I have to idea of how to build PDF using latex. Will look into it

**Comment by brechtm** [comment] 2020-07-17 13:28
Closing since this is very likely bug in Sphinx's napoleon extension. Please do add a comment if there's anything new to report.

**Closed by brechtm** 2020-07-17 13:28 UTC
Labels: bug, crash

**Comment by thiagocrepaldi** [comment] 2020-07-17 19:39
agreed, thank you!

**Comment by rsandler00** [comment] 2021-09-10 19:10
I also had this issue and the problem for me was that I did not have a function summary before args, so going from:

```
        """
        Args:
            train_dset: Dataset object

        Returns:
            val_acc: (float) best validation accuracy
            val_loss: (float) best validation loss
            results_dict: (dict) results dict of eval. See eval()
        """
```

to 

```
        """
        Trains classifier

        Args:
            train_dset: Dataset object

        Returns:
            val_acc: (float) best validation accuracy
            val_loss: (float) best validation loss
            results_dict: (dict) results dict of eval. See eval()
        """
```

fixed the problem
