### ISSUE TITLE
rinohtype crashes when processing .png file

### ISSUE THREAD

**Issue by JonSilverman** [brechtm/rinohtype#165] opened 2020-06-19 21:14 UTC
1. TeX Gyre Pagella does not include a normal medium upright font. Falling back to normal regular upright
 25% [==========                              ] ETA 00:06 (00:02) page 1
Exception occurred:
  File "/usr/local/lib/python3.7/site-packages/rinoh/flowable.py", line 261, in flow_inner
    padded_width = content_width + padding_h
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

2. Error log included. Also included conf.py, intro.rst which has directive to figure and .png. png file created using gimp.

[sphinx-err-o8pvp1k6.log](https://github.com/brechtm/rinohtype/files/4806690/sphinx-err-o8pvp1k6.log)

[Archive.zip](https://github.com/brechtm/rinohtype/files/4806710/Archive.zip)

Please also provide the following information:
* rinohtype version: (output from `rinoh --version`)
* Sphinx version: (output from `sphinx-build --version`)
* Python version: (output from `python --version`)
* operating system: (Windows, Linux, MacOS)

**Comment by vivlav** [comment] 2020-06-23 12:04
I have same error on Windows.
python --version
    Python 3.8.3

rinoh --version
    rinoh 0.4.0 (2020-03-05)

sphinx-build --version
    sphinx-build 3.1.1

**Comment by brechtm** [comment] 2020-06-23 14:01
This looks like a duplicate of #153. Please try with the master branch of rinohtype.

**Comment by JonSilverman** [comment] 2020-06-23 14:19
I am running on macOS. Has this been successfully tested previously. Is there a min config required in terms of attributes for image / figure directive in the .rst file?

Jon

**Comment by brechtm** [comment] 2020-06-23 14:34
I verified that #153 was fixed in the master branch, of course. Have you tried installing rinohtype from the master branch? You can install it directly from GitHub like this:

    pip install git+https://github.com/brechtm/rinohtype.git@master

If the crash still occurs with the master version, you can attach the source files to this issue and I'll have a look. Thanks!

**Comment by JonSilverman** [comment] 2020-06-25 15:06
Downloaded master branch build, raw and it failed with different error message. See below from trace. All files to recreate where previously uploaded with the bug report.

'rinoh_documents' config variable not set, automatically converting from 'latex_documents'

processing packagemanagement... index intro sys_pkgmgr app_pkgmgr resolving references...

rendering... 




Exception occurred:

  File "/usr/local/lib/python3.7/site-packages/rinoh/frontend/sphinx/__init__.py", line 230, in write_doc

    rinoh_tree = parser.from_doctree(doctree['source'], doctree,
AttributeError: 'ReStructuredTextReader' object has no attribute 'from_doctree'
Jon 

    On Tuesday, June 23, 2020, 09:34:37 AM CDT, Brecht Machiels <notifications@github.com> wrote:  
 
 


I verified that #153 was fixed in the master branch, of course. Have you tried installing rinohtype from the master branch? You can install it directly from GitHub like this:
pip install git+https://github.com/brechtm/rinohtype.git@master

If the crash still occurs with the master version, you can attach the source files to this issue and I'll have a look. Thanks!

**Comment by brechtm** [comment] 2020-06-25 15:26
> ```
> Exception occurred:
>    File "/usr/local/lib/python3.7/site-packages/rinoh/frontend/sphinx/__init__.py", line 230, in write_doc     rinoh_tree = parser.from_doctree(doctree['source'], doctree,
> AttributeError: 'ReStructuredTextReader' object has no attribute 'from_doctree'
> ```

Sorry about that. You caught the master branch at a point where I broke it 😞. That issue is fixed in the meantime.

When building the project you provided (I had to rename `intro.rst` to `index.rst` though), I run into yet another issue:

```
Exception occurred:
  File "/private/tmp/issue165/site-packages/rinoh/backend/pdf/cos.py", line 363, in <genexpr>
    for key, value in self.items())
AttributeError: 'str' object has no attribute 'bytes'
```

I'll look into that and get back to you.

**Comment by brechtm** [comment] 2020-06-25 23:07
The AttributeError would only occur on Python < 3.7, but this is fixed now. Please try again after installing rinohtype from the master branch?

**Comment by JonSilverman** [comment] 2020-06-26 01:35
Just did quick test .. works.
Thanks

Jon

**Comment by brechtm** [comment] 2020-06-26 10:12
> The AttributeError would only occur on Python < 3.7, but this is fixed now.

Oops. In fact is was a problem with PyPy3.6-7.3.0, not CPython <3.7.

**Closed by brechtm** 2020-06-26 10:12 UTC
Labels: bug, crash

**Comment by JonSilverman** [comment] 2020-06-27 14:46
BTW, I am using Python 3.7.7

Jon
