### ISSUE TITLE
empty PDF files generated

### ISSUE THREAD

**Issue by davidedelvento** [brechtm/rinohtype#57] opened 2016-08-22 16:57 UTC
After the installation described in issue #56 running as follows generate a 12-page practically empty PDF file:
- most pages are totally blank
- some pages have a line or two on the top of bottom
- some pages have a box or a table (without content)
- page 11 has two shaded boxes (one yellow, the other grey)

```
$ rinoh demo.txt 
demo.txt:89: (ERROR/3) Undefined substitution referenced: "problematic".
demo.txt:547: (ERROR/3) Undefined substitution referenced: "*** Expect 6 errors (including this one). ***".
demo.txt:346: (ERROR/3) Unknown target name: "5".
demo.txt:355: (ERROR/3) Unknown target name: "nonexistent".
demo.txt:380: (ERROR/3) Unknown target name: "hyperlink reference without a target".
demo.txt:393: (ERROR/3) Duplicate target name, cannot be used as a unique reference: "duplicate target names".
The 'pygments' package is not available; cannot perform syntax highlighting of CodeBlocks.
rinohtype 0.2.1 (2016-08-18)  Copyright (c) Brecht Machiels
This program comes with ABSOLUTELY NO WARRANTY. Its use is subject
to the terms of the GNU Affero General Public License version 3.
TeX Gyre Pagella has no Normal Medium Upright style available. Falling back to Normal Regular Upright
[None:None <image>] Error opening image file: [Errno 2] No such file or directory: '/tmp/images/biohazard.png'
[None:None <system_message>] demo.txt:6: (INFO/1) Enumerated list start value not ordinal-1: "3" (ordinal 3) (page 6)
[None:None <system_message>] demo.txt:6: (INFO/1) Enumerated list start value not ordinal-1: "C" (ordinal 3) (page 6)
[None:None <system_message>] demo.txt:6: (INFO/1) Enumerated list start value not ordinal-1: "iii" (ordinal 3) (page 6)
TeX Gyre Cursor has no Normal Medium Upright style available. Falling back to Normal Regular Upright
[demo.txt:391 <system_message>] demo.txt:391: (INFO/1) Duplicate implicit target name: "duplicate target names". (page 10)
[demo.txt:None <reference>] Error opening image file: [Errno 2] No such file or directory: '/tmp/images/title.png'
[None:None <image>] Error opening image file: [Errno 2] No such file or directory: '/tmp/images/title.png'
100% [========================================] ETA 00:00 (00:04)
Not yet converged, rendering again...
100% [========================================] ETA 00:00 (00:03)
Writing output: demo.pdf
```

**Comment by brechtm** [comment] 2016-08-22 21:21
This is likely a bug in your PDF viewer. See the comments near the bottom of #2 to find out which minimum version of poppler or PDF.js you require. Or are you using a non-poppler-based PDF viewer?

**Comment by davidedelvento** [comment] 2016-08-22 21:59
I'm using atril v1.12.2 and it shows http://www.mos6581.org/rinohtype/_downloads/demo.pdf just fine, just not the one I generate myself

**Comment by brechtm** [comment] 2016-08-23 06:29
That's no good! Can you attach the PDF you generated so I can inspect it?

**Comment by davidedelvento** [comment] 2016-08-23 15:12
Here it is: [demo.pdf](https://github.com/brechtm/rinohtype/files/432789/demo.pdf)
Now double checking what you said before, I tried opening that file from the Chrome browser, and it looks ok there, so maybe you are right that it is (at least in part) a bug in the PDF viewer, but you may want to investigate why my attachment is different from the one on the website.

**Comment by brechtm** [comment] 2016-08-23 15:26
Oops. I forgot that the demo.pdf included with the documentation makes use of the the core PDF fonts (the "base 14 fonts") so it doesn't need to embed fonts (the PDF reader is responsible for providing the fonts). This is because it uses the "sphinx_base14" style sheet (see `rinoh --list-stylesheets`).

When you generate a PDF using `rinoh`, it defaults to the "sphinx_article" style sheet, employing fonts that are embedded in the PDF file.

I see that atril depends on poppler. So it is probably using a poppler version older than 0.41.

**Comment by brechtm** [comment] 2016-10-07 16:00
@davidedelvento Were you able to test with a newer poppler version? If so, does that solve the problem?

**Comment by davidedelvento** [comment] 2016-10-10 21:36
No, I have not been able to do that. Compiling a dependency of my PDF reader is something low in my priority list, sorry (and my distro hasn't updated that either)

**Comment by brechtm** [comment] 2016-10-11 07:47
Ok. I think it's safe to assume this problem is indeed caused by the poppler bug, so I'm closing this issue. Please re-open when it turns out there is another cause.

**Closed by brechtm** 2016-10-11 07:47 UTC
